version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - cd HomeFinderBackend
      - pip install -r requirements.txt
  pre_build:
    commands:
      - python manage.py collectstatic --noinput
      - python manage.py makemigrations
      - python manage.py migrate
  build:
    commands:
      - echo "Build phase completed."
  post_build:
    commands:
      - echo "Deployment complete."
artifacts:
  files:
    - '**/*'
  discard-paths: no
