version: 0.2

phases:
  install:
    commands:
      - echo "Installing system dependencies..."
      - yum install -y gcc openssl-devel bzip2-devel libffi-devel zlib-devel make
      - echo "Removing existing pyenv directory if it exists..."
      - rm -rf /root/.pyenv
      - echo "Installing pyenv..."
      - curl https://pyenv.run | bash
      - export PATH="$HOME/.pyenv/bin:$PATH"
      - eval "$(pyenv init --path)"
      - eval "$(pyenv init -)"
      - eval "$(pyenv virtualenv-init -)"
      - echo "Setting environment variables for OpenSSL..."
      - export LDFLAGS="-L/usr/lib64"
      - export CPPFLAGS="-I/usr/include"
      - export PKG_CONFIG_PATH="/usr/lib64/pkgconfig"
      - echo "Installing Python 3.12..."
      - pyenv install 3.12.0
      - pyenv global 3.12.0
      - echo "Python 3.12 installed."

  pre_build:
    commands:
      - echo "Installing Python packages..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running collectstatic..."
      - python manage.py collectstatic --noinput

artifacts:
  files:
    - '**/*'
  discard-paths: no