# Generated by Django 5.1.4 on 2024-12-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], default='sale', max_length=10),
        ),
    ]
