# Generated by Django 5.1.4 on 2024-12-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=10),
        ),
    ]
