# Generated by Django 5.1.4 on 2025-01-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
