# Generated by Django 5.1.4 on 2025-01-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_isverified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='isVerified',
            new_name='is_verified',
        ),
    ]
