# Generated by Django 5.1.4 on 2025-03-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_reservation_property_reservation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
